### ISSUE TITLE
Ability to enable GraphiQL on a RouteBuilder

### ISSUE THREAD

**Issue by Samsv77** [alexsteinerde/graphiql-vapor#9]
It would be great to be able to enable GraphiQL on a route builder, for example if I do,

```
let altRoute = app.grouped(...)
altRoute.enableGraphiQL()
```

The code change is small, instead of making an extension of Application, we would do an extension of RouteBuilder.

**Comment by alexsteinerde** [comment]
That's a good idea. I ask myself why I haven't done this in the first place.
I'll create a PR once I find the time.

**Comment by alexsteinerde** [comment]
@Samsv77 What do you think about PR #10?

**Comment by Samsv77** [comment]
Looks good to me!
